# Drop item scenario - tests the drop command
# Validates that items can be dropped from inventory with state verification
scenario:
  name: "Drop Item"
  description: "Test drop command with inventory state verification"
  seed: 42043
  config:
    max_commands: 20
    timeout: 60
    demo_mode: true

  setup:
    - "dump_state"  # Get initial state

  steps:
    # Step 1: Check initial inventory to confirm items are present
    - command: "inventory"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "inventory command should work"

    # Step 2: Get detailed state to verify initial item count
    - command: "dump_state"
      wait_for: "inventory"
      assertions:
        - type: CONTENT_PRESENT
          field: "inventory"
          value: true
          message: "Inventory should be present"

    # Step 3: Drop a Health Potion
    - command: "drop Health Potion"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "drop command should succeed"

    # Step 4: Verify inventory was updated
    - command: "dump_state"
      assertions:
        - type: CONTENT_PRESENT
          field: "inventory"
          value: true
          message: "Inventory should still exist after dropping item"

    # Step 5: Check inventory to confirm item was dropped
    - command: "inventory"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "inventory command should still work after drop"
