# Equip/unequip scenario - tests equipment management
# Validates equip/unequip for weapons and armor with state verification
# Demo mode starts with Iron Sword and Leather Armor equipped
scenario:
  name: "Equip and Unequip"
  description: "Test weapon and armor equip/unequip with state verification"
  seed: 42005
  config:
    max_commands: 25
    timeout: 90
    demo_mode: true

  setup:
    - "dump_state"  # Get initial state

  steps:
    # Step 1: Check initial inventory and equipment
    - command: "inventory"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "inventory command should work"

    # Step 2: Verify equipped weapon state (Iron Sword equipped in demo)
    - command: "dump_state"
      wait_for: "inventory"
      assertions:
        - type: CONTENT_PRESENT
          field: "equipped_weapon"
          value: true
          message: "Weapon should be equipped initially"

    # Step 3: Unequip current weapon
    - command: "unequip weapon"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "unequip weapon command should succeed"

    # Step 4: Verify weapon is now in inventory (unequipped)
    - command: "dump_state"
      assertions:
        - type: CONTENT_PRESENT
          field: "inventory"
          value: true
          message: "Inventory should contain unequipped weapon"

    # Step 5: Check inventory shows the unequipped weapon
    - command: "inventory"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "inventory command should show unequipped weapon"

    # Step 6: Re-equip the weapon
    - command: "equip Iron Sword"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "equip weapon command should succeed"

    # Step 7: Verify weapon is equipped again
    - command: "dump_state"
      assertions:
        - type: CONTENT_PRESENT
          field: "equipped_weapon"
          value: true
          message: "Weapon should be equipped after equip command"

    # Step 8: Unequip armor
    - command: "unequip armor"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "unequip armor command should succeed"

    # Step 9: Verify armor state change
    - command: "dump_state"
      assertions:
        - type: CONTENT_PRESENT
          field: "inventory"
          value: true
          message: "Inventory should exist after unequipping armor"

    # Step 10: Re-equip armor
    - command: "equip Leather Armor"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "equip armor command should succeed"

    # Step 11: Verify final equipment state
    - command: "dump_state"
      assertions:
        - type: CONTENT_PRESENT
          field: "equipped_armor"
          value: true
          message: "Armor should be equipped after equip command"
