# Equip/unequip scenario - tests equipment management
# Validates that the player can equip and unequip items
scenario:
  name: "Equip and Unequip"
  description: "Test equip and unequip commands for gear management"
  seed: 42005
  config:
    max_commands: 20
    timeout: 60

  setup:
    - "dump_state"  # Get initial state

  steps:
    # Step 1: Check inventory
    - command: "inventory"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "inventory command should work"

    # Step 2: Get detailed state
    - command: "dump_state"
      wait_for: "inventory"
      assertions:
        - type: CONTENT_PRESENT
          field: "location"
          value: true
          message: "Location should be present"

    # Step 3: Check equipment status
    - command: "equip"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "equip command should be valid"

    # Step 4: Check unequip
    - command: "unequip"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "unequip command should be valid"

    # Step 5: Verify state
    - command: "dump_state"
      assertions:
        - type: STATE_RANGE
          field: "health"
          value:
            min: 1
            max: 200
          message: "Health should remain valid after equipment changes"
