# Use item scenario - tests consumable item usage
# Validates that the player can use items from inventory
scenario:
  name: "Use Item"
  description: "Test use command for consumable items"
  seed: 42006
  config:
    max_commands: 20
    timeout: 60

  setup:
    - "dump_state"  # Get initial state

  steps:
    # Step 1: Check inventory
    - command: "inventory"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "inventory command should work"

    # Step 2: Get detailed state
    - command: "dump_state"
      wait_for: "inventory"
      assertions:
        - type: CONTENT_PRESENT
          field: "location"
          value: true
          message: "Location should be present"

    # Step 3: Try using an item (may not have items yet)
    - command: "use"
      assertions:
        - type: COMMAND_VALID
          field: ""
          value: true
          message: "use command should be recognized"

    # Step 4: Check state after use attempt
    - command: "dump_state"
      assertions:
        - type: STATE_RANGE
          field: "health"
          value:
            min: 1
            max: 200
          message: "Health should be in valid range"
